# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-Pngslimmer
version:      0.22
version_from: lib/Image/Pngslimmer.pm
installdirs:  site
requires:
    Compress::Raw::Zlib:           2.003
    Compress::Zlib:                2.003
    POSIX:                         1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
